/*
AuditBoard Developer Portal API Documentation

Testing RegionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package auditboard

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/dja852/auditboard-go-client"
)

func Test_auditboard_RegionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RegionsAPIService RegionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RegionsAPI.RegionsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionsAPIService RegionsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RegionsAPI.RegionsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionsAPIService RegionsRegionIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var regionId int64

		resp, httpRes, err := apiClient.RegionsAPI.RegionsRegionIdDelete(context.Background(), regionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionsAPIService RegionsRegionIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var regionId int64

		resp, httpRes, err := apiClient.RegionsAPI.RegionsRegionIdGet(context.Background(), regionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionsAPIService RegionsRegionIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var regionId int64

		resp, httpRes, err := apiClient.RegionsAPI.RegionsRegionIdPut(context.Background(), regionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
