/*
AuditBoard Developer Portal API Documentation

External API reference documentation.

API version: 23.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auditboard

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// EsgMetricValuesAPIService EsgMetricValuesAPI service
type EsgMetricValuesAPIService service

type ApiEsgMetricValuesEsgMetricValueIdDeleteRequest struct {
	ctx context.Context
	ApiService *EsgMetricValuesAPIService
	esgMetricValueId int64
}

func (r ApiEsgMetricValuesEsgMetricValueIdDeleteRequest) Execute() (*EsgMetricValues, *http.Response, error) {
	return r.ApiService.EsgMetricValuesEsgMetricValueIdDeleteExecute(r)
}

/*
EsgMetricValuesEsgMetricValueIdDelete Method for EsgMetricValuesEsgMetricValueIdDelete

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param esgMetricValueId Model id
 @return ApiEsgMetricValuesEsgMetricValueIdDeleteRequest
*/
func (a *EsgMetricValuesAPIService) EsgMetricValuesEsgMetricValueIdDelete(ctx context.Context, esgMetricValueId int64) ApiEsgMetricValuesEsgMetricValueIdDeleteRequest {
	return ApiEsgMetricValuesEsgMetricValueIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		esgMetricValueId: esgMetricValueId,
	}
}

// Execute executes the request
//  @return EsgMetricValues
func (a *EsgMetricValuesAPIService) EsgMetricValuesEsgMetricValueIdDeleteExecute(r ApiEsgMetricValuesEsgMetricValueIdDeleteRequest) (*EsgMetricValues, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EsgMetricValues
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EsgMetricValuesAPIService.EsgMetricValuesEsgMetricValueIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/esg_metric_values/{esg_metric_value_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"esg_metric_value_id"+"}", url.PathEscape(parameterValueToString(r.esgMetricValueId, "esgMetricValueId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEsgMetricValuesEsgMetricValueIdGetRequest struct {
	ctx context.Context
	ApiService *EsgMetricValuesAPIService
	esgMetricValueId int64
	include *[]string
}

// Possible sideloaded relationships
func (r ApiEsgMetricValuesEsgMetricValueIdGetRequest) Include(include []string) ApiEsgMetricValuesEsgMetricValueIdGetRequest {
	r.include = &include
	return r
}

func (r ApiEsgMetricValuesEsgMetricValueIdGetRequest) Execute() (*EsgMetricValues, *http.Response, error) {
	return r.ApiService.EsgMetricValuesEsgMetricValueIdGetExecute(r)
}

/*
EsgMetricValuesEsgMetricValueIdGet Method for EsgMetricValuesEsgMetricValueIdGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param esgMetricValueId Model id
 @return ApiEsgMetricValuesEsgMetricValueIdGetRequest
*/
func (a *EsgMetricValuesAPIService) EsgMetricValuesEsgMetricValueIdGet(ctx context.Context, esgMetricValueId int64) ApiEsgMetricValuesEsgMetricValueIdGetRequest {
	return ApiEsgMetricValuesEsgMetricValueIdGetRequest{
		ApiService: a,
		ctx: ctx,
		esgMetricValueId: esgMetricValueId,
	}
}

// Execute executes the request
//  @return EsgMetricValues
func (a *EsgMetricValuesAPIService) EsgMetricValuesEsgMetricValueIdGetExecute(r ApiEsgMetricValuesEsgMetricValueIdGetRequest) (*EsgMetricValues, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EsgMetricValues
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EsgMetricValuesAPIService.EsgMetricValuesEsgMetricValueIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/esg_metric_values/{esg_metric_value_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"esg_metric_value_id"+"}", url.PathEscape(parameterValueToString(r.esgMetricValueId, "esgMetricValueId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.include != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include", r.include, "form", "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEsgMetricValuesEsgMetricValueIdPutRequest struct {
	ctx context.Context
	ApiService *EsgMetricValuesAPIService
	esgMetricValueId int64
	esgMetricValuesPut *EsgMetricValuesPut
}

func (r ApiEsgMetricValuesEsgMetricValueIdPutRequest) EsgMetricValuesPut(esgMetricValuesPut EsgMetricValuesPut) ApiEsgMetricValuesEsgMetricValueIdPutRequest {
	r.esgMetricValuesPut = &esgMetricValuesPut
	return r
}

func (r ApiEsgMetricValuesEsgMetricValueIdPutRequest) Execute() (*EsgMetricValues, *http.Response, error) {
	return r.ApiService.EsgMetricValuesEsgMetricValueIdPutExecute(r)
}

/*
EsgMetricValuesEsgMetricValueIdPut Method for EsgMetricValuesEsgMetricValueIdPut

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param esgMetricValueId Model id
 @return ApiEsgMetricValuesEsgMetricValueIdPutRequest
*/
func (a *EsgMetricValuesAPIService) EsgMetricValuesEsgMetricValueIdPut(ctx context.Context, esgMetricValueId int64) ApiEsgMetricValuesEsgMetricValueIdPutRequest {
	return ApiEsgMetricValuesEsgMetricValueIdPutRequest{
		ApiService: a,
		ctx: ctx,
		esgMetricValueId: esgMetricValueId,
	}
}

// Execute executes the request
//  @return EsgMetricValues
func (a *EsgMetricValuesAPIService) EsgMetricValuesEsgMetricValueIdPutExecute(r ApiEsgMetricValuesEsgMetricValueIdPutRequest) (*EsgMetricValues, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EsgMetricValues
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EsgMetricValuesAPIService.EsgMetricValuesEsgMetricValueIdPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/esg_metric_values/{esg_metric_value_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"esg_metric_value_id"+"}", url.PathEscape(parameterValueToString(r.esgMetricValueId, "esgMetricValueId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.esgMetricValuesPut
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEsgMetricValuesGetRequest struct {
	ctx context.Context
	ApiService *EsgMetricValuesAPIService
	include *[]string
}

// Possible sideloaded relationships
func (r ApiEsgMetricValuesGetRequest) Include(include []string) ApiEsgMetricValuesGetRequest {
	r.include = &include
	return r
}

func (r ApiEsgMetricValuesGetRequest) Execute() (*EsgMetricValuesGet200Response, *http.Response, error) {
	return r.ApiService.EsgMetricValuesGetExecute(r)
}

/*
EsgMetricValuesGet Method for EsgMetricValuesGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiEsgMetricValuesGetRequest
*/
func (a *EsgMetricValuesAPIService) EsgMetricValuesGet(ctx context.Context) ApiEsgMetricValuesGetRequest {
	return ApiEsgMetricValuesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EsgMetricValuesGet200Response
func (a *EsgMetricValuesAPIService) EsgMetricValuesGetExecute(r ApiEsgMetricValuesGetRequest) (*EsgMetricValuesGet200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EsgMetricValuesGet200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EsgMetricValuesAPIService.EsgMetricValuesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/esg_metric_values"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.include != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include", r.include, "form", "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEsgMetricValuesPostRequest struct {
	ctx context.Context
	ApiService *EsgMetricValuesAPIService
	esgMetricValuesPostRequest *EsgMetricValuesPostRequest
}

func (r ApiEsgMetricValuesPostRequest) EsgMetricValuesPostRequest(esgMetricValuesPostRequest EsgMetricValuesPostRequest) ApiEsgMetricValuesPostRequest {
	r.esgMetricValuesPostRequest = &esgMetricValuesPostRequest
	return r
}

func (r ApiEsgMetricValuesPostRequest) Execute() (*EsgMetricValuesGet200Response, *http.Response, error) {
	return r.ApiService.EsgMetricValuesPostExecute(r)
}

/*
EsgMetricValuesPost Method for EsgMetricValuesPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiEsgMetricValuesPostRequest
*/
func (a *EsgMetricValuesAPIService) EsgMetricValuesPost(ctx context.Context) ApiEsgMetricValuesPostRequest {
	return ApiEsgMetricValuesPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EsgMetricValuesGet200Response
func (a *EsgMetricValuesAPIService) EsgMetricValuesPostExecute(r ApiEsgMetricValuesPostRequest) (*EsgMetricValuesGet200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EsgMetricValuesGet200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EsgMetricValuesAPIService.EsgMetricValuesPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/esg_metric_values"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.esgMetricValuesPostRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
