/*
AuditBoard Developer Portal API Documentation

External API reference documentation.

API version: 23.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auditboard

import (
	"encoding/json"
)

// checks if the AllowedTeamsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllowedTeamsPostRequest{}

// AllowedTeamsPostRequest struct for AllowedTeamsPostRequest
type AllowedTeamsPostRequest struct {
	AllowedTeam *AllowedTeams `json:"allowed_team,omitempty"`
}

// NewAllowedTeamsPostRequest instantiates a new AllowedTeamsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllowedTeamsPostRequest() *AllowedTeamsPostRequest {
	this := AllowedTeamsPostRequest{}
	return &this
}

// NewAllowedTeamsPostRequestWithDefaults instantiates a new AllowedTeamsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllowedTeamsPostRequestWithDefaults() *AllowedTeamsPostRequest {
	this := AllowedTeamsPostRequest{}
	return &this
}

// GetAllowedTeam returns the AllowedTeam field value if set, zero value otherwise.
func (o *AllowedTeamsPostRequest) GetAllowedTeam() AllowedTeams {
	if o == nil || IsNil(o.AllowedTeam) {
		var ret AllowedTeams
		return ret
	}
	return *o.AllowedTeam
}

// GetAllowedTeamOk returns a tuple with the AllowedTeam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllowedTeamsPostRequest) GetAllowedTeamOk() (*AllowedTeams, bool) {
	if o == nil || IsNil(o.AllowedTeam) {
		return nil, false
	}
	return o.AllowedTeam, true
}

// HasAllowedTeam returns a boolean if a field has been set.
func (o *AllowedTeamsPostRequest) HasAllowedTeam() bool {
	if o != nil && !IsNil(o.AllowedTeam) {
		return true
	}

	return false
}

// SetAllowedTeam gets a reference to the given AllowedTeams and assigns it to the AllowedTeam field.
func (o *AllowedTeamsPostRequest) SetAllowedTeam(v AllowedTeams) {
	o.AllowedTeam = &v
}

func (o AllowedTeamsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllowedTeamsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowedTeam) {
		toSerialize["allowed_team"] = o.AllowedTeam
	}
	return toSerialize, nil
}

type NullableAllowedTeamsPostRequest struct {
	value *AllowedTeamsPostRequest
	isSet bool
}

func (v NullableAllowedTeamsPostRequest) Get() *AllowedTeamsPostRequest {
	return v.value
}

func (v *NullableAllowedTeamsPostRequest) Set(val *AllowedTeamsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAllowedTeamsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAllowedTeamsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllowedTeamsPostRequest(val *AllowedTeamsPostRequest) *NullableAllowedTeamsPostRequest {
	return &NullableAllowedTeamsPostRequest{value: val, isSet: true}
}

func (v NullableAllowedTeamsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllowedTeamsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


