/*
AuditBoard Developer Portal API Documentation

External API reference documentation.

API version: 23.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auditboard

import (
	"encoding/json"
)

// checks if the ProcessesPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessesPostRequest{}

// ProcessesPostRequest struct for ProcessesPostRequest
type ProcessesPostRequest struct {
	Process *Processes `json:"process,omitempty"`
}

// NewProcessesPostRequest instantiates a new ProcessesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessesPostRequest() *ProcessesPostRequest {
	this := ProcessesPostRequest{}
	return &this
}

// NewProcessesPostRequestWithDefaults instantiates a new ProcessesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessesPostRequestWithDefaults() *ProcessesPostRequest {
	this := ProcessesPostRequest{}
	return &this
}

// GetProcess returns the Process field value if set, zero value otherwise.
func (o *ProcessesPostRequest) GetProcess() Processes {
	if o == nil || IsNil(o.Process) {
		var ret Processes
		return ret
	}
	return *o.Process
}

// GetProcessOk returns a tuple with the Process field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessesPostRequest) GetProcessOk() (*Processes, bool) {
	if o == nil || IsNil(o.Process) {
		return nil, false
	}
	return o.Process, true
}

// HasProcess returns a boolean if a field has been set.
func (o *ProcessesPostRequest) HasProcess() bool {
	if o != nil && !IsNil(o.Process) {
		return true
	}

	return false
}

// SetProcess gets a reference to the given Processes and assigns it to the Process field.
func (o *ProcessesPostRequest) SetProcess(v Processes) {
	o.Process = &v
}

func (o ProcessesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessesPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Process) {
		toSerialize["process"] = o.Process
	}
	return toSerialize, nil
}

type NullableProcessesPostRequest struct {
	value *ProcessesPostRequest
	isSet bool
}

func (v NullableProcessesPostRequest) Get() *ProcessesPostRequest {
	return v.value
}

func (v *NullableProcessesPostRequest) Set(val *ProcessesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessesPostRequest(val *ProcessesPostRequest) *NullableProcessesPostRequest {
	return &NullableProcessesPostRequest{value: val, isSet: true}
}

func (v NullableProcessesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


